### ISSUE TITLE
X chromosome in r10 dysfunctional

### ISSUE THREAD

**Issue by Fedja** [FINNGEN/pheweb#453]
variant page errors out: https://r10.finngen.fi/variant/23-153635030-C-T

and gene page associations never load. 
https://r10.finngen.fi/gene/DUSP9

This will probably be fixed with the upcoming update to latest master?

**Comment by anastasia-shch** [comment]
Update to master probably will not fix this. It looks like it is connected to the long format file - it contains chromosome X instead of 23 in variant positions (R11 and R12 have 23 and work fine). R10 longformat file was generated with nextflow when the development for the longformat mode was ongoing whereas for later releases we used cromwell version of the pipeline incorporated to the import wdl. So there seem to be some differences with the later longformat releases. I will check more on that and fix the file!

**Comment by Fedja** [comment]
ok great if its fixed by reimport with new data.
